# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: NiZiN_invest # jekyll-seo-tag > Owners twitter username
author: NiZiN_invest # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: NiZiN Invest # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/NiZiN_invest
    - https://github.com/NiZiN-invest
markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!--more--> # Marks end of excerpt in posts
timezone: America/Fortaleza # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "Nossas Postagens, Artigos e Estudos" # The post list page content
    feature_text: |
      Bem vindo ao nosso Blog
    image:
      feature: "assets/images/financas_investimentos/Header_NiZiN_Investimentos.png"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: article  # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: pt-BR # Set the site language
title: "NiZiN Investimentos" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo@144px.png" # Site logo, also used in jekyll-seo-tag
description: "NiZiN Investimentos é uma iniciativa que reune desenvolvedores e analistas para produzir código para ciência de dados com foco em investimentos e finanças." # Site description and default description, also used in jekyll-seo-tag
url: "https://nizin-invest.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/nizin-invest"
email: "nizin-invest@gmail.com"
disqus: "nizin-investimentos" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
google_analytics: "G-44ZKG4FJDF"
ads:
  show: True
  client: ca-pub-1710447158146560  
# google_analytics_anonymize_ip: ""
service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Inicio
  url: /
- title: Postagens
  url: /blog/
- title: Categorias
  url: /categories/
- title: Pesquisa
  url: /search/

navigation_footer:
- title: Carlos Delfino
  url: https://carlosdelfino.eti.br
- title: CIEDA
  url: https://cieda.com.br

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/NiZiN_invest
  #LinkedIn: https://www.linkedin.com/in/daviddarnes
  GitHub: https://github.com/nizin-invest
  BuymeaCoffe: https://buymeacoffee.com/carlosdelfino#support
  #link: https://darn.es
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  buymeacoffe: True
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap

math:
  inline:
    start: ($
    end: $)
